# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4207d4e32daa857066ee163a397fda5a23c76d223d4f8b096c28a5d1373ee6732874129efe17d7d79ea20999214093ff60aa3803732d931d6ad90b103c1fba

test:
  secret_key_base: f081538015a64a089073887921014034539f3d48ef0bd62b81045c97d64d32dcdf1fd8defea987260c47d7b834b1344b9b0b8b71f0344b177f0ecaf713e4de8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
